EPC_FEAT_SELECTION:
  [
    "ADDRESS1",
    "POSTCODE",
    "POSTTOWN",
    "MAINS_GAS_FLAG",
    "NUMBER_HABITABLE_ROOMS",
    "LOCAL_AUTHORITY_LABEL",
    "TRANSACTION_TYPE",
    "CURRENT_ENERGY_RATING",
    "POTENTIAL_ENERGY_RATING",
    "CURRENT_ENERGY_EFFICIENCY",
    "ENERGY_CONSUMPTION_CURRENT",
    "TENURE",
    "MAINHEAT_ENERGY_EFF",
    "SHEATING_ENERGY_EFF",
    "HOT_WATER_ENERGY_EFF",
    "FLOOR_ENERGY_EFF",
    "WINDOWS_ENERGY_EFF",
    "WALLS_ENERGY_EFF",
    "ROOF_ENERGY_EFF",
    "MAINHEATC_ENERGY_EFF",
    "LIGHTING_ENERGY_EFF",
    "MAINHEAT_DESCRIPTION",
    "CO2_EMISSIONS_CURRENT",
    "CO2_EMISS_CURR_PER_FLOOR_AREA",
    "LIGHTING_COST_CURRENT",
    "LIGHTING_COST_POTENTIAL",
    "HEATING_COST_CURRENT",
    "HEATING_COST_POTENTIAL",
    "HOT_WATER_COST_CURRENT",
    "HOT_WATER_COST_POTENTIAL",
    "BUILDING_REFERENCE_NUMBER",
    "LODGEMENT_DATE",
    "INSPECTION_DATE",
    "BUILT_FORM",
    "PROPERTY_TYPE",
    "CONSTRUCTION_AGE_BAND",
    "TRANSACTION_TYPE",
    "MAIN_FUEL",
    "TOTAL_FLOOR_AREA",
    "ENERGY_TARIFF",
    "SOLAR_WATER_HEATING_FLAG",
    "FLOOR_HEIGHT",
    "WIND_TURBINE_COUNT",
    "PHOTO_SUPPLY",
    "FLOOR_LEVEL",
    "NUMBER_HEATED_ROOMS",
    "MECHANICAL_VENTILATION",
    "MAIN_HEATING_CONTROLS",
    "MULTI_GLAZE_PROPORTION",
    "GLAZED_TYPE",
    "GLAZED_AREA",
    "EXTENSION_COUNT",
    "SECONDHEAT_DESCRIPTION",
    "ADDRESS2",
    "LMK_KEY",
    "UPRN",
    "HOTWATER_DESCRIPTION",
    "FLOOR_DESCRIPTION",
    "WINDOWS_DESCRIPTION",
    "WALLS_DESCRIPTION",
    "ROOF_DESCRIPTION",
    "MAINHEAT_DESCRIPTION",
    "LIGHTING_DESCRIPTION",
  ]

FIGURE_OUT: "outputs/figures/"
SUPERVISED_MODEL_FIG_PATH: "outputs/figures/"
KEPLER_CONFIG_PATH: "outputs/kepler/configs/"
KEPLER_MAP_PATH: "outputs/kepler/maps/"
